apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster2
  region: us-east-1

vpc:
  id: vpc-0cda97cf5fac49ac0
  cidr: "192.168.0.0/16"
  subnets:
    public:
      spm-api-stack-PublicSubnet01:
        id: subnet-0024da187b0e89831
      spm-api-stack-PublicSubnet02:
        id: subnet-0a65630dfe892e8dd
    private:
      spm-api-stack-PrivateSubnet01:
        id: subnet-010d4afc55b98beb0
      spm-api-stack-PrivateSubnet02:
        id: subnet-070e604e0e84bd00d

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2